# Generated by Django 2.1.3 on 2018-12-03 06:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.EmailField(max_length=254)),
                ('email_type', models.IntegerField(choices=[(1, 'Home'), (2, 'Business')], verbose_name='email type')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('groups', models.ManyToManyField(to='app.Group', verbose_name='Groups')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('\\d{9}|\\d{3} \\d{3} \\d{3}', 'Invalid number pattern')])),
                ('phone_type', models.IntegerField(choices=[(1, 'Home'), (2, 'Business')], verbose_name='Phone type')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Person', verbose_name='Phone number')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(to='app.Person', verbose_name='Group members'),
        ),
        migrations.AddField(
            model_name='email',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Person', verbose_name='email adress'),
        ),
    ]
