# Generated by Django 2.1.3 on 2018-12-03 07:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, to='app.Person', verbose_name='Group members'),
        ),
        migrations.AlterField(
            model_name='person',
            name='groups',
            field=models.ManyToManyField(blank=True, to='app.Group', verbose_name='Groups'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('\\d{9}|\\d{3} \\d{3} \\d{3}', 'Invalid number pattern')]),
        ),
        migrations.AlterField(
            model_name='phone',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Person', verbose_name='Person'),
        ),
    ]
