# Generated by Django 2.1.3 on 2018-12-03 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181203_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{9}S|^\\d{3} \\d{3} \\d{3}$', 'Invalid number pattern')]),
        ),
    ]
