# Generated by Django 2.1.3 on 2018-12-03 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181203_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{9}$|^\\d{3} \\d{3} \\d{3}$', 'Invalid number pattern')], verbose_name='Phone number'),
        ),
    ]
