# Generated by Django 2.1.3 on 2018-12-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181203_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='adress',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
